// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: auth.proto

package server

import (
	"context"

	"zero-demo/rpc/auth/auth"
	"zero-demo/rpc/auth/internal/logic"
	"zero-demo/rpc/auth/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Ping(ctx context.Context, in *auth.Request) (*auth.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
